# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'alienacr'
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        repository: $(repoName)
        tags: |
          $(tag)
    - task: ArtifactoryDocker@1
      inputs:
        command: 'push'
        artifactoryService: 'Art_SVC_conn'
        targetRepo: '$(repoName)'
        imageName: '$(imageName):$(tag)'
    